---
version: '3.8'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 5
  user_api:
    build:
      context: py/projects/user_api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    image: kodawari/user_api
    hostname: user_api
    container_name: user_api
    depends_on:
      cassandra:
        condition: service_healthy

