FROM python:3.11.1-buster
COPY . .
WORKDIR /py/projects/user_api
RUN pip3 install poetry
RUN poetry install --only main --no-root
CMD ["poetry", "run", "uvicorn", "main:app", "--app-dir", "user_api/", "--host", "0.0.0.0"]
