FROM python:3.11.1-buster
COPY . .
WORKDIR /py/projects/user_api
RUN pip3 install poetry
RUN poetry install --only main --no-root
ARG USER_API_PORT_ARG
ENV USER_API_PORT=$USER_API_PORT_ARG
ENTRYPOINT poetry run uvicorn main:app --app-dir user_api/ --host 0.0.0.0 --port ${USER_API_PORT}
